// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absolute': string;
  'align-baseline': string;
  'align-center': string;
  'd-flex': string;
  'flex-column': string;
  'flex-row': string;
  'justify-center': string;
  'main': string;
  'relative': string;
}
export const cssExports: CssExports;
export default cssExports;
