// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'widget-temperature': string;
  'widget-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
