// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'col-6': string;
  'pl-10': string;
  'pl-4': string;
  'pr-10': string;
  'row': string;
  'widget-max-width': string;
  'widget-settings': string;
  'widget-temperature': string;
  'widget-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
